apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    release: beta
    type: poc
  name: helloworld-deployment2
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      type: poc
  template: 
    metadata: 
      labels: 
        release: beta
        type: poc
      name: helloworld-pod
    spec: 
      containers: 
        - image: "asif97/hello-world-node:v1"
          name: helloworld-container
          ports: 
            - containerPort: 8080
