name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Specify the desired Node version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start
          minikube kubectl -- get pods -n kube-system
          kubectl config use-context minikube

      - name: Build Docker image
        run: docker build -t asif97/hello-world-node:v2 .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u asif97 -p 18R!c@9O$^3KCeM
          docker push asif97/hello-world-node:v2

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/helloworld-deployment2 helloworld-container=asif97/hello-world-node:v2

  # Add a new step to update the deployment
  update-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Kubernetes Deployment
        run: |
          sed -i 's|image: "asif97/hello-world-node:v1"|image: "asif97/hello-world-node:v2"|' dev/deployment.yaml
          kubectl apply -f dev/deployment.yaml
